[workspace]
resolver = "3"
members = ["supernovas-sys", "supernovas"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/kiranshila/supernovas_rs"
authors = ["Kiran Shila"]

[workspace.dependencies]
supernovas-sys = { path = "supernovas-sys", version = "0.1.0" }
