//! Raw bindgen FFI bindings to the [SuperNOVAS](https://github.com/sigmyne/supernovas) C library.
//!
//! These bindings are auto-generated by `bindgen` at build time. Use the
//! [`supernovas`](https://docs.rs/supernovas) crate for a safe, idiomatic Rust
//! wrapper. Only reach into this crate directly when you need to call a
//! SuperNOVAS function that the safe wrapper doesn't yet expose.
//!
//! # Feature flags
//!
//! - **`vendored`** - build the bundled SuperNOVAS v1.7 static library from
//!   the git submodule at `vendor/supernovas`. Requires a C compiler and CMake.
//!   The vendored build always sets `WITHOUT_CURL=ON` (no libcurl dependency)
//!   and respects the `libc` feature (see below).
//! - **`calceph`** - expose the CALCEPH ephemeris integration symbols.
//!   With `vendored`: the CMake build automatically enables `ENABLE_CALCEPH=ON`.
//!   With a system library: the installed SuperNOVAS **must** have been compiled
//!   with CALCEPH support (cmake `-DENABLE_CALCEPH=ON`); otherwise the
//!   `libsolsys-calceph` symbols will be missing at link time.
//! - **`libc`** - controls the `WITHOUT_LIBC` CMake flag for the **vendored**
//!   build only. When absent, SuperNOVAS is compiled without any libc calls
//!   (suitable for freestanding/embedded targets). Has no effect on system
//!   library builds. Implied by the `std` feature of the `supernovas` wrapper.
//!
//! # System library requirements
//!
//! When `vendored` is not enabled, a pre-installed SuperNOVAS is used. It must
//! satisfy:
//!
//! | Requirement | Detail |
//! |---|---|
//! | Version | `>= 1.7.0` - required for `novas_set_error_handler` (error capture) |
//! | CALCEPH support | Only if the `calceph` feature is enabled: compiled with `-DENABLE_CALCEPH=ON` |
//! | libc | Standard build (not `WITHOUT_LIBC`); the `libc` feature flag has no effect |
//!
//! The version is checked automatically via `pkg-config`.  Use
//! `SUPERNOVAS_INCLUDE_DIR` / `SUPERNOVAS_LIB_DIR` to point at a manual
//! install, or `SUPERNOVAS_NO_PKG_CONFIG=1` to skip `pkg-config` entirely.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all, clippy::pedantic)]
// bindgen preserves raw C doc comments including bare URLs and [unit] notation
// (e.g. "[deg]", "[rad]") that rustdoc interprets as intra-doc links.
// Suppress both lint classes for this generated-code crate.
#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::broken_intra_doc_links)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
