//! Raw bindgen FFI bindings to the [SuperNOVAS](https://github.com/sigmyne/supernovas) C library.
//!
//! These bindings are auto-generated by `bindgen` at build time. Use the
//! [`supernovas`](https://docs.rs/supernovas) crate for a safe, idiomatic Rust
//! wrapper. Only reach into this crate directly when you need to call a
//! SuperNOVAS function that the safe wrapper doesn't yet expose.
//!
//! # Feature flags
//!
//! - **`vendored`** — build the bundled SuperNOVAS v1.6.0 static library from
//!   the git submodule at `vendor/supernovas`. Requires a C compiler and CMake.
//! - *(default, no `vendored`)* — link against a system-installed SuperNOVAS
//!   located via `pkg-config` (`>= 1.6.0`). Override with
//!   `SUPERNOVAS_INCLUDE_DIR` / `SUPERNOVAS_LIB_DIR` env vars.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all, clippy::pedantic)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
