[package]
name = "supernovas"
description = "Safe Rust wrapper around the SuperNOVAS astrometry library"
keywords = ["astronomy", "astrometry", "coordinates", "novas"]
categories = ["science", "no-std"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true

[features]
default = []
vendored = ["supernovas-ffi/vendored"]

[dependencies]
supernovas-ffi = { workspace = true }
thiserror = { version = "2", default-features = false }
approx = { version = "0.5", default-features = false }
